### ISSUE TITLE
Error message related with sub-process of optimizer

### ISSUE THREAD

**Issue by annsonic** [automl/HPOlib#116]
Dear HPOlib team,

Thanks for providing such useful tool!
But I am confused why I always get error messages in certain system call sub-process, even when I just test on the default benchmark - branin.
The optimization result seems working.
Should I ignore these error messages? Or do you have other solutions?
Thank you very much.

* My system is Ubuntu 14.04.
* HPOlib is installed by following "Installing inside an virtualenv" instruction.

* for TPE(hyperopt_august2013_mod) sampled error message: 
[INFO] [09:33:04:537:HPOlib.wrapping] Starting configuration   199, fold  0
[ERR]:[INFO] [09:33:04:HPOlib.cv] Result for ParamILS: SAT, 0.050142, 1, 48.760473, 0, python ../branin.py
[ERR]:
[ERR]:[ERROR] [09:33:04:HPOlib.cv] [INFO] [09:33:04:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
[ERR]:[INFO] [09:33:04:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.050142, 1, 48.760473, 0, python ../branin.py
[ERR]:
[ERR]:[INFO] [09:33:04:HPOlib.cv] Finished CV
[ERR]:[INFO] [09:33:04:HPOlib.cv] Result: 48.760473
[INFO] [09:33:04:970:HPOlib.wrapping] Result  48.760473, current best   0.415899
[INFO] [09:33:06:018:HPOlib.wrapping] -----------------------END--------------------------------------

* for SMAC sampled error message from log-warn23.txt: 
09:44:57.836 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x000B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [09:44:57:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
09:44:57.988 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x000B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [09:44:57:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 0.074295, 1, 24.129964, -1, python ../branin.py

**Comment by mfeurer** [comment]
Dear annsonic,

Great to hear that you find HPOlib useful.

Indeed, these error messages aren't real errors. They are rather logs of 
what's happening in the optimization procedure. As long as the 
optimization results are fine in the end, you can simply ignore them.

Best,
Matthias

**Comment by annsonic** [comment]
Dear Matthias,

Got it. Thank you once again.
