### ISSUE TITLE
Test performance

### ISSUE THREAD

**Issue by KEggensperger** [automl/HPOlib#38]
Having optimized an algorithm one might be interested in the test performance of the found configuration. 
``HPOlib-run`` could have an additional ``--validate`` flag that calls the target algorithm with the best found configuration params, e.g. ``<anyBenchmarkWrapper>.py --params -a 23 -b -0.1234 --test``. This wrapper now loads it's testdata and returns test performance.
This is optional for a benchmark, but can be useful for evaluation.

Questions:
  * How do we handle the computing time of this single run? Training on the whole training/validation data might take longer than any of previous runs? 
  * If specified number of runs, is this a run?
  * If specified a wallclock-time, how to know when to start calculating the test performance
  * Rather implement a ``HPOlib-test`` script that calls the benchmark with the best configuration found in a .pkl file?
  * Only validate offline?

**Comment by mfeurer** [comment]
Added in aa9ed09943733fd8042f74dbddd03a5e7af744b5

Answers:
* All runs are performed sequential. This can take very long.
* The test is done offline, so it does not count towards any numbers/time limits.
