### ISSUE TITLE
HPOlib test gets stuck

### ISSUE THREAD

**Issue by aaronkl** [automl/HPOlib#82]
I started HPOlib test on a SMAC run via: 
HPOlib-testbest --all --cwd esmac_2_08_00-development_1200_2015-1-25--13-55-51-9883/

Afterwards it produces the following output and then it gets stuck:

[INFO] [13:06:08:HPOlib.check_before_start] Check config.cfg..
[WARNING] [13:06:08:HPOlib.check_before_start] There is no config.cfg in esmac_2_08_00-development_1200_2015-1-25--13-55-51-9883/, all options need to be provided as CLI arguments
[INFO] [13:06:08:HPOlib.check_before_start] ..passed
[INFO] [13:06:08:HPOlib.check_before_start] Check dependencies:
[INFO] [13:06:08:HPOlib.check_before_start] Runsolver..
[INFO] [13:06:08:HPOlib.check_before_start] ..passed
[INFO] [13:06:08:HPOlib.check_before_start] Check python_modules..
[WARNING] [13:06:08:HPOlib.check_before_start] Theano not found. You might need this to run some more complex benchmarks!
[WARNING] [13:06:08:HPOlib.check_before_start] CUDA not in $PATH
[INFO] [13:06:08:HPOlib.check_before_start] ..passed

I do not understand why it says that it cannot find a config.cfg files as a config.cfg files does exist in this directory

**Comment by mfeurer** [comment]
The message that it cannot find a configuration looks like a bug. But this does not explain why the test script gets stuck. Can you please
* check if HPOlib-test is really stuck and no target algorithm is running (by default, the script does not output anything. You can change this by setting HPOlib_loglevel = 10 in the HPOLIB section of the config.cfg file).
* Add several print statements to narrow down where HPOlib-test gests stuck.

**Comment by mfeurer** [comment]
@aaronkl anything new on this issue?

**Comment by mfeurer** [comment]
@aaronkl anything new on this issue?
