### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by albahnsen** [automl/HPOlib#95]
when installing using `python setup.py install` I got the error
```
> python setup.py install
  File "setup.py", line 42
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by mfeurer** [comment]
Hm, I have never seen this before. Which python version do you use?

**Comment by albahnsen** [comment]
Python 3.4.3

**Comment by mfeurer** [comment]
Okay, we didn't try HPOlib with python 3.X yet. Please give us some time to think about how to handle this.

**Comment by albahnsen** [comment]
Great thanks. I will use it with python2.7 then.

**Comment by mfeurer** [comment]
I started a new issue for python 3.X: #96
