### ISSUE TITLE
Installation fails on OSX (10.10.4, python 2.7.10)

### ISSUE THREAD

**Issue by saihttam** [automl/HPOlib#97]
Trying to install for auto-sklearn - previous installs for auto-sklearn worked fine (HPOlibConfigSpace0.1dev, paramsklearn)
Installing using; "sudo pip install git+https://github.com/automl/HPOlib#egg=HPOlib0.2"

Fails with:

...
    Running command /usr/bin/python -c "import setuptools;__file__='/private/tmp/pip_build_root/HPOlib0.2/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fFUI3L-record/install-record.txt --single-version-externally-managed
    running install
    sed: -i may not be used with stdin

    [INFO] 'runsolver' not found, so we try to install it

    Downloading runsolver from http://www.cril.univ-artois.fr/~roussel/runsolver/runsolver-3.3.4.tar.bz2, saving to /private/tmp/pip_build_root/HPOlib0.2/runsolver-3.3.4.tar.bz2

    Extracting runsolver to /private/tmp/pip_build_root/HPOlib0.2/runsolver-3.3.4
....
Building runsolver

Replace a line, which seems to cause trouble on 32 bit systems'

Replacing did not work: Command 'sed -i 's|gnu/asm/unistd_$(WSIZE).h|gnu/asm/unistd_$(WSIZE).h  /usr/include/i386-linux-gnu/asm/unistd_$(WSIZE).h|' runsolver/src/Makefile' returned non-zero exit status 1
...
error: file '/private/tmp/pip_build_root/HPOlib0.2/runsolver/src/runsolver' does not exist

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools;__file__='/private/tmp/pip_build_root/HPOlib0.2/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fFUI3L-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/tmp/pip_build_root/HPOlib0.2

**Comment by mfeurer** [comment]
Hi,
I am sorry to tell you that HPOlib will not work on any OSX/MAC system and we neither have the manpower nor the test systems to enable this.

Since auto-sklearn does not require any of HPOlibs functionality to run as a drop-in replacement for scikit-learn, you can try running auto-sklearn without HPOlib. Nevertheless, auto-sklearn requires the runsolver tool and I do not know whether runsolver runs on OSX/MAC.
